name: Feature request
description: Suggest an idea for this project
assignees:
  - LISPlaysYT
body:
  - type: input
    id: is-it-related-to-a-problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: input
    id: describe-the-solution
    attributes:
      label: Describe the solution you would like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: input
    id: describe-alternatives
    attributes:
      label: Describe alternatives you have considered
      description: A clear and concise description of any alternative solutions or features you have considered.
    validations:
      required: true
  - type: input
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here. 
        To include images, drag and drop them into the comment box after submitting the issue or send a link to the image.
    validations:
      required: false
